name: Package

on:
  push:
    tags: "*"

jobs:
  package:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch all branch and tag history
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Name Release
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_SECRET }}

      - name: Build and push
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # do not checkout a fresh copy of repo
          context: .
          push: true
          target: runner
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            quay.io/team-helium/blockchain-node:${{ steps.docker-tag.outputs.tag }}

      - name: Image digest
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: echo ${{ steps.docker_build.outputs.digest }}
